version: '3.9'

volumes:
  mysqldata:

services:
  api:
    image: node:16.15.1-alpine
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      NODE_ENV: local
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: nodejs-project
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "yarn install && yarn dev"

  mysql:
    image: mysql:8.0.23
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: nodejs-project
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 2s
      retries: 10

  front:
    image: node:16.15.1-alpine
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
    working_dir: /app
    environment:
      HOST: 0.0.0.0
    command: |
      sh -c "
        apk update && \
        apk upgrade && \
        apk add --no-cache make gcc git g++ python3 && \
        yarn install && \
        yarn dev
      "
